# Generated by Django 4.2 on 2023-05-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('meta_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.meta_data')),
            ],
        ),
    ]
