# Generated by Django 4.2 on 2023-05-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.page'),
        ),
        migrations.AddField(
            model_name='content',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='published_at',
            field=models.DateTimeField(null=True),
        ),
    ]
