# Generated by Django 4.2 on 2023-05-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_content_page_content_published_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(default='content', max_length=200),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(default='changeMe', max_length=200),
        ),
    ]
