# Generated by Django 4.2 on 2023-05-03 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contentmodule_rename_content_contentblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodule',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.contentblock'),
        ),
    ]
