# Generated by Django 4.2 on 2023-05-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_contentmodule_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodule',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
