# Generated by Django 4.2 on 2023-05-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_contentmodule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodule',
            name='position',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
