# Generated by Django 4.2 on 2023-05-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_contentmodule_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmodule',
            name='imageContent',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='contentmodule',
            name='textContent',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
