# Generated by Django 4.2 on 2023-05-03 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_meta_data_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentBlock',
            new_name='Content_Block',
        ),
        migrations.RenameModel(
            old_name='ContentModule',
            new_name='Content_Module',
        ),
    ]
