# Generated by Django 4.2 on 2023-05-03 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_rename_contentblock_content_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta_data',
            name='image',
        ),
    ]
