# Generated by Django 4.2 on 2023-05-03 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_remove_page_content_blocks_content_block_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content_module',
            old_name='imageContent',
            new_name='image_content',
        ),
        migrations.RenameField(
            model_name='content_module',
            old_name='textContent',
            new_name='text_content',
        ),
        migrations.AddField(
            model_name='content_module',
            name='image_alt',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content_block',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_blocks', to='blog.page'),
        ),
    ]
