# Generated by Django 4.2 on 2023-05-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_imagecontent_content_module_image_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta_data',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content_module',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_modules', to='blog.content_block'),
        ),
    ]
