# Generated by Django 4.2 on 2023-05-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_meta_data_image_alter_content_module_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_module',
            name='image_content',
        ),
        migrations.RemoveField(
            model_name='meta_data',
            name='image',
        ),
    ]
