# Generated by Django 4.2 on 2023-05-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_content_module_image_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta_data',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content_module',
            name='text_content',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
