# Generated by Django 4.2 on 2023-05-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_meta_data_image_alter_content_module_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_module',
            name='image_content',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='content_module',
            name='image_alt',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
