# Generated by Django 4.2 on 2023-05-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_content_module_image_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta_data',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='meta_data',
            name='heading',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
